development:
  sessions:
    default:
      database: locomotive_heroku_dev
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: locomotive_heroku_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        identity_map_enabled: true


# defaults: &defaults
#   host: localhost
#   port: 27017
#   # slaves:
#   #   - host: slave1.local
#   #     port: 27018
#   #   - host: slave2.local
#   #     port: 27019

# development:
#   <<: *defaults
#   database: locomotive_heroku_dev

# test:
#   <<: *defaults
#   database: locomotive_heroku_test